# Generated by Django 4.1.7 on 2023-03-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingPostcode',
        ),
    ]
